# 语言文件[可选 中文简体:zh_CN]
language: zh_CN

# 是否开启更新提醒,建议开启
isCheckUpdate: true

# op登录时候是否发送更新提醒
isCheckUpdateToOpMsg: true

# 多久异步同步一次数据并刷新排行榜 单位秒(改动需重启生效)
# 如果设置为0,不会执行同步操作
task: 60

# 排行榜是否过滤 op true过滤, false不过滤
isOp: false

# 是否自动启动服务器时候初始化一次数据(获取全部玩家),之后只刷新在线玩家的排行数据 true开启，false关闭
isInit: false

# 黑名单,该名单内的玩家会被过滤掉(请不要在服务器只有一个人的情况下填自己)
blacklist:
  - "CMI-Fake-Operator"

# papi需要过滤的值(只能为数字) 如果变量获取到这个值就会过滤掉
filter:
  - ''

# 根据内部api获取的排行数据
# 这些数据 可以使用 /pt createHd [类型] 指令生成全息排行榜
# 类型意义可在 https://ricedoc.handyplus.cn/wiki/PlayerTop/command/ 查看
enable:
  vault: true
  playerPoints: true
  playerTitleCoin: true
  playerTitleNumber: true
  playerTaskCoin: true
  playerGuildMoney: true
  playerGuildKill: true
  playerGuildDie: true
  playerGuildDonatedMoney: true
  mcMmo: true
  mcMmoAcrobatics: true
  mcMmoAlchemy: true
  mcMmoArchery: true
  mcMmoAxes: true
  mcMmoExcavation: true
  mcMmoFishing: true
  mcMmoHerbalism: true
  mcMmoMining: true
  mcMmoRepair: true
  mcMmoSalvage: true
  mcMmoSmelting: true
  mcMmoSwords: true
  mcMmoTaming: true
  mcMmoUnarmed: true
  mcMmoWoodcutting: true
  mcMmoCrossbows: false
  mcMmoMaces: false
  mcMmoTridents: false
  jobsBrewer: true
  jobsBuilder: true
  jobsCrafter: true
  jobsDigger: true
  jobsEnchanter: true
  jobsExplorer: true
  jobsFarmer: true
  jobsFisherman: true
  jobsHunter: true
  jobsMiner: true
  jobsWeaponSmith: true
  jobsWoodcutter: true